volumes:
  db:
  redis:
  cert_cache:
  soundboard:

networks:
  default:

services:
  app:
    build:
      context: ../
      dockerfile: yagpdb_docker/Dockerfile

    restart: unless-stopped

    command:
      - "-all"
      - "-pa"
      - "-exthttps=true"
      - "-https=false"

    depends_on:
      - redis
      - db

    networks:
      - default

    volumes:
      - cert_cache:/app/cert
      - soundboard:/app/soundboard

    environment:
      YAGPDB_OWNER: ${YAGPDB_OWNER}
      YAGPDB_CLIENTID: ${YAGPDB_CLIENTID}
      YAGPDB_CLIENTSECRET: ${YAGPDB_CLIENTSECRET}
      YAGPDB_BOTTOKEN: ${YAGPDB_BOTTOKEN}
      YAGPDB_HOST: ${YAGPDB_HOST}

      YAGPDB_PQHOST: db
      YAGPDB_PQUSERNAME: yagpdb
      YAGPDB_PQPASSWORD: ${POSTGRES_PASSWORD}

      YAGPDB_REDIS: redis:6379

  redis:
    image: docker.io/redis
    restart: unless-stopped

    networks:
      - default

    volumes:
      - redis:/data

  db:
    image: docker.io/postgres:11
    restart: unless-stopped

    networks:
      - default

    volumes:
      - db:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: yagpdb
      POSTGRES_USER: yagpdb
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
